<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2 class="text-danger">Email ja cadastrado</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/inscreverse" class="btn btn-primary btn-block">Voltar</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  