<script src="/src/js/remove_tweet.js"></script>
<script src="/src/js/show_pag_tweet.js"></script>
<script src="/src/js/change_pag.js"></script>
<script src="/src/js/add_new_tweet.js"></script>
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logoff">
	  		Sair
	  	</a>
			<img src="/src/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->perfil->name ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil->total_tweets ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil->total_following ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil->total_followers ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6" id="tweets">
			<div class="row mb-2 create-tweet-div">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" id="tweet_content" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="button" class="btn btn-primary" id="create_tweet">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!-- LISTING ALL TWEETS -->
			


			<!-- Model for ajax -->
			<div id="_tweet" style="display:none;">
				<div class="row tweet">
					<div class="col">
						<p><strong class="tweet_user_name"></strong> <span class="text text-muted">-<small class="tweet_data">  </small> </span></p>
						<p class="tweet_content"></p>

						<br />
						<form>
							<div class="col d-flex justify-content-end">

								<button type="button" class="btn btn-danger button-remove" ><small>Remover</small></button>
							</div>
						</form>
					</div>
				</div>
			</div>

			<!-- pagination menus's button -->
			<div class="row">
			<nav aria-label="...">
			<ul class="pagination">
				<li class="page-item first">
				<a class="page-link" href="" tabindex="-1">First</a>
				</li>

				

				<li class="page-item last">
				<a class="page-link" href="">Last</a>
				</li>
			</ul>
			</nav>

			</div>

		</div>
		



		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/who_follow" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="model">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Exluir</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Deseja realmente excluir esse tweet?.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" id="del_yes">Sim</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="del_no">Voltar</button>
      </div>
    </div>
  </div>
</div>
