<script>
	let tweet_id;
	let tweet;
	//delete tweet
	$(document).ready(()=>{
		$("#tweets").on("click",".button-remove",(e)=>{
			$(".modal").slideToggle(100);
			//get the id of the tweet that was clicked
			tweet_id = $(e.target).closest('button').attr('id');
			tweet = $(e.target).closest('.tweet');
		})
		$("#del_yes").on("click",()=>{
			//and do a request to delete_tweet that will delete it from the db, just when the model "Yes" be clicked
			$.ajax({
				type:'POST',
				url:'php/delete_tweet.php',
				data: 'tweet_id='+tweet_id,
				success: (e)=>{
					tweet.remove();
				}, //if the request is sucess i'll delete the tweet from the timeline with jquery
				error: ()=>{console.log('nao foi')},
			})
			$(".modal").slideToggle(100);
		})
		//Close the modal
		$("#del_no").on("click",()=>{
			$(".modal").slideToggle(100);
		})
		$(".close").on("click",()=>{
			$(".modal").slideToggle(100);
		})
		
	})

	

</script>
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logoff">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6" id="tweets">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!-- LISTING ALL TWEETS -->
			<?php foreach($this->view->tweets AS $tweet){ ?>
			<div class="row tweet">
				<div class="col">
					<p><strong><?=  $tweet->_name ?></strong> <span class="text text-muted">-<small> <?=  $tweet->date ?> </small> </span></p>
					<p><?=  $tweet->tweet ?></p>

					<br />
					<form>
						<div class="col d-flex justify-content-end">
							<button type="button" class="btn btn-danger button-remove" id="<?=$tweet->id?>"><small>Remover</small></button>
						</div>
					</form>
				</div>
			</div>

			<?php } ?>




		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="#" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="model">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Exluir</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Deseja realmente excluir esse tweet?.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" id="del_yes">Sim</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="del_no">Voltar</button>
      </div>
    </div>
  </div>
</div>
