<script src="src/js/search_user.js"></script>
<script src="src/js/follow_unfollow.js"></script>
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logoff">
	  		Sair
	  	</a>
			<img src="/src/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5" id=container>
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->perfil->name ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil->total_tweets ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil->total_following ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil->total_followers ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="#"> <!-- action="/who_follow" -->
								<div class="input-group mb-3">
									<input type="text" class="form-control" placeholder="Quem você está procurando?" id="search_user">
									<div class="input-group-append">
										<button class="btn btn-primary" type="button" id="btn_search_user">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<!-- Results -->
	
			<section id="results">
				<div class="row mb-2  user" >
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6" id="name">
										
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											
											<a href="/action?action=unfollow&&id=" class="btn btn-danger unfollow" >Deixar de seguir</a>
											
											<a href="/action?action=follow&&id=" class="btn btn-success follow">Seguir</a>
											

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section id="user_searched_model" style="display:none">
				<div class="row mb-2  user" >
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6" id="name">
										
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											
											<a href="/action?action=unfollow&&id=" class="btn btn-danger unfollow" >Deixar de seguir</a>
											
											<a href="/action?action=follow&&id=" class="btn btn-success follow">Seguir</a>
											

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			

			

		</div>
	</div>
</div>